- name: variables example
  hosts: localhost
  vars:
    USERNAME: "viswanath"
    LOCATION: "allagadda"
  tasks:
  - name: variables task-1
    vars:
      LOCATION: "Hyberabad"
    ansible.builtin.debug:
      msg: "My name is {{USERNAME}} and location is {{LOCATION}}"
