- name: data types practice
  hosts: localhost
  vars:
    Technologies:
    - Devops
    - ansible
    - jenkins
    Skill:
      devops: 7
      ansible: 2
      jenkins: 3
  tasks:
  - name: data list types
    ansible.builtin.debug:
      msg: "{{Skill}}"

  - name: data map types
    ansible.builtin.debug:
      msg: "{{Technologies}}""