- name: conditions practice
  hosts: localhost
  tasks:
  - name: conditon for user check
    ansible.builtin.command:
      id viswa
      # useradd viswa
    register: result

  - name: print value
    ansible.builtin.debug:
      msg: "result"
