- name: conditions practice
  hosts: localhost
  tasks:
  - name: conditon for user check
    ansible.builtin.command:
      # id viswa1
      useradd viswa1
    register: result
    ignore_errors: True

  - name: print value
    ansible.builtin.debug:
      msg: "{{result}} {{result.rc}}"
