- name: conditions practice
  hosts: localhost
  tasks:
  - name: conditon for user check
    ansible.builtin.command:
      id viswa1
      # useradd viswa1
    register: result
    ignore_errors: True

  - name: print value
    ansible.builtin.debug:
      msg: "{{result}} and {{result.rc}}"

  - name: conditon for user check
    ansible.builtin.user:
      name: viswa2
    when: result.rc != 0