- name: loops practice
  hosts: localhost
  tasks:
  - name: loop values print
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'git' , state: 'present'}
    - {name: "ansible" , state: "present"}
    - {name: 'jenkins' , state: 'present'}